[supabase]
url = "https://bochkjykezvrlbbivzgv.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvY2hranlrZXp2cmxiYml2emd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwNzE1MDgsImV4cCI6MjA3NjY0NzUwOH0.YMfC70lHAAuGPXKGcdGM0pbSyJQWCTVfp24Ip_nGFCw"
