# .streamlit/secrets.toml (APENAS PARA USO LOCAL OU PARA COPIAR NO PAINEL SECRETS DO STREAMLIT CLOUD)

[supabase]
# Substitua pelo URL da sua API no Supabase
url = "https://bochkjykezvrlbbivzgv.supabase.co"
# Substitua pela sua chave 'anon' ou 'service_role' (a 'anon' é mais comum e segura para apps públicos)
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvY2hranlrZXp2cmxiYml2emd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwNzE1MDgsImV4cCI6MjA3NjY0NzUwOH0.YMfC70lHAAuGPXKGcdGM0pbSyJQWCTVfp24Ip_nGFCw"
