# .streamlit/secrets.toml (APENAS PARA USO LOCAL OU PARA COPIAR NO PAINEL SECRETS DO STREAMLIT CLOUD)

[supabase]
# Substitua pelo URL da sua API no Supabase
url = "https://jiuacegblmqcpwiwowds.supabase.co" 
# Substitua pela sua chave 'anon' ou 'service_role' (a 'anon' é mais comum e segura para apps públicos)
key = "sb_publishable_Q5_f3mZME4y_7gMxs1IoBA_u1WImXiR"
